### ISSUE TITLE
Write a simple core singing/verification algorithm

### ISSUE THREAD

**Issue by pawelprazak** [codem8s/autograph#1]
Couple of functions for signing and verification with unit tests.

**Comment by antoniaklja** [comment]
good start - https://www.mlgblockchain.com/crypto-signature.html
In general we would like to use asymmetric encryption (private key to generate signature and public key for verifying)

**Comment by antoniaklja** [comment]
it also looks interesting:
Digital Signature Algorithm https://golang.org/pkg/crypto/dsa/
example of unit testing https://golang.org/src/crypto/dsa/dsa_test.go

**Comment by antoniaklja** [comment]
the question is RSA vs DSA
https://security.stackexchange.com/questions/5096/rsa-vs-dsa-for-ssh-authentication-keys

TLDR
* DSA is faster for signature generation but slower for validation
* Never use DSA or ECDSA.
* RSA is the best
