### ISSUE TITLE
Figure out how to hook up the core verifier to the kubernetes api

### ISSUE THREAD

**Issue by pawelprazak** [codem8s/autograph#5]
This would essentially be `run` command implementation.

Note that TLS will be required.

**Comment by antoniaklja** [comment]
It might be good start - https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks

**Comment by antoniaklja** [comment]
good example how to implement the admission review webhook
https://github.com/caesarxuchao/example-webhook-admission-controller/blob/master/main.go#L33
